#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &


bspc config border_width         2
bspc config window_gap           8 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


# Auto Start Applications

sh ~/.config/openbox/scripts/wallpaper_refresh.sh random &

MONITOR=DP-1 polybar &
if xrandr | grep -w -q "DP-1 connected"; then
  xrandr --output eDP-1 --mode 1680x1050 --scale 1.0x1.0 --pos 0x0 --output DP-1 --auto --pos 1680x0

  bspc monitor eDP-1 -d 1 2 3 4 5
  bspc monitor  DP-1 -d 6 7 8 9 0

  # DP-1已连接，设置polybar到DP-1
  MONITOR=DP-1 polybar main &
else
  xrandr --output eDP-1 --mode 1680x1050 --scale 1.0x1.0 --pos 0x0

  bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 0

  # 否则使用eDP-1
  MONITOR=eDP-1 polybar main &
fi


# turn off bee sound
xset b off &

picom -b &
dunst &
polybar &
nm-applet &

# Launch Fcitx5 Input Method Framework
fcitx5 &
