# https://github.com/radleylewis/dotfiles/blob/master/.config/alacritty/alacritty.toml

# Themes:
# https://github.com/alacritty/alacritty-theme
[general]
import = [
    "~/.config/alacritty/themes/themes/dracula_plus.toml"
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
builtin_box_drawing = true
size = 11.5

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
style = "SemiBold"

[font.italic]
style = "Light"



[window]
decorations = "full"
opacity = 1

[colors.primary]
background = "#221a0f"
foreground = "#d3af86"

[colors.normal]
black = "#221a0f"
red = "#c87e5a"
green = "#879a6b"
yellow = "#e4b581"
blue = "#5d90cd"
magenta = "#c792ea"
cyan = "#6bbab2"
white = "#d3af86"

[colors.bright]
black = "#7d6f48"
red = "#c87e5a"
green = "#879a6b"
yellow = "#e4b581"
blue = "#5d90cd"
magenta = "#c792ea"
cyan = "#6bbab2"
white = "#f2cca8"
